server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 27duyanh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG